[clang-tidy] Add cert-msc24-c checker.
steakhal/llvm-project pull request #3
Opened 2021-11-11 13:36 UTC by futog

Checks for deprecated and obsolescent functions listed in CERT C Coding
Standard Recommendation MSC24-C.

For the listed functions, an alternative, more secure replacement is
suggested, if available. The checker heavily relies on the functions
from annex K (Bounds-checking interfaces) of C11.

2021-11-11 17:06 UTC, steakhal requested changes
The best way of testing the macro detection stuff is to have a single test file, but multiple `RUN` lines with different `CHECK-PREFIX`-es to expect messages at different scenarios.
Something like this:

```
// RUN: clang-tidy %s -checks='-*,cert-msc24-c' -U__STDC_LIB_EXT1__   -U__STDC_WANT_LIB_EXT1__   | FileCheck %s --check-prefix=MESSAGES_WITHOUT_ANNEX_K
// RUN: clang-tidy %s -checks='-*,cert-msc24-c' -D__STDC_LIB_EXT1__=1 -U__STDC_WANT_LIB_EXT1__   | FileCheck %s --check-prefix=MESSAGES_WITHOUT_ANNEX_K
// RUN: clang-tidy %s -checks='-*,cert-msc24-c' -U__STDC_LIB_EXT1__   -D__STDC_WANT_LIB_EXT1__=1 | FileCheck %s --check-prefix=MESSAGES_WITHOUT_ANNEX_K
// RUN: clang-tidy %s -checks='-*,cert-msc24-c' -D__STDC_LIB_EXT1__=1 -D__STDC_WANT_LIB_EXT1__=1 | FileCheck %s

(void)gets(s);
// CHECK-MESSAGES_WITHOUT_ANNEX_K: :[[@LINE-1]]:9: warning: function 'gets' is deprecated as of C99, removed from C11. [cert-msc24-c]
// matched on both the MESSAGES_WITHOUT_ANNEX_K prefix and on the default CHECK-MESSAGES prefix as well.

(void)freopen(s, s, f);
// CHECK-MESSAGES: :[[@LINE-1]]:9: warning: function 'freopen' has no exclusive access to file, 'freopen_s' should be used instead. [cert-msc24-c]
// matched only on the default FileCheck.
```

2021-11-11 17:06 UTC, steakhal commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  if (useSafeFunctionsFromAnnexK() &&
So, for each function call you encounter during the AST visitation you will again-and-again re-check if the std library provides annex K and the user actually wants it.
I think it's fairly safe to assume that the preprocessor macros driving this decision should not change after encountering the first call. You should cache this.
BTW `mutable` can help you _constify_ the member functions, it's a rare but useful use of that this time.

2021-11-11 17:06 UTC, steakhal commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +      doesReplacementFromAnnexKExist(FunctionName))
I would rather use this name `doesReplacementFromAnnexKExistFor(...)`

2021-11-15 11:14 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +namespace {
done

2021-11-17 13:05 UTC, steakhal requested changes
I really like it. It's in great shape, and you are almost at the end.
I found a couple of readability stuff but nothing more.

2021-11-17 13:05 UTC, steakhal commented on clang-tools-extra/test/clang-tidy/checkers/cert-msc24-c.c
> +  //no-warning
// no-warning
..^ space

2021-11-21 16:03 UTC, futog commented on clang-tools-extra/test/clang-tidy/checkers/cert-msc24-c.c
> +  //no-warning
done

2021-11-22 10:20 UTC, steakhal requested changes
Minor nits.

2021-11-22 10:20 UTC, steakhal commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +          to(functionDecl(hasAnyNameFromSet(FunctionNamesWithAnnexKReplacement))
In the previous matcher, you passed fully qualified names, but in this one, you have unqualified names.
This seems weird. Please investigate.

2021-11-22 10:20 UTC, steakhal commented on clang-tools-extra/docs/clang-tidy/checks/cert-msc24-c.rst
> +`qsort`, `setbuf`, `snprintf`, `sprintf`,  `sscanf`, `strcat`, `strcpy`, `strerror`,
`setbuf` is included in the list, while `rewind` is not. You should probably omit this one too since a subsequent section explicitly mentions this - together with the `rewind`.

2021-11-22 10:20 UTC, steakhal commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  assert(Loc.isValid() && "Invalid location.");
Although it seems fine, I would probably simply return here instead of asserting this.

2021-11-22 10:46 UTC, steakhal commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  assert(Loc.isValid() && "Invalid location.");
Add a `FIXME: I'm not sure if this can ever happened, but let's be on the safe side.`

2021-11-22 12:32 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  return ast_matchers::internal::HasNameMatcher(FunctionNames)
ast_matcher:: is needed here
std::move added

2021-11-22 12:33 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  return ast_matchers::internal::HasNameMatcher(FunctionNames)
ast_matcher is needed here.
std::move added

2021-11-22 12:33 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  Finder->addMatcher(
done

2021-11-22 12:34 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  Finder->addMatcher(
done

2021-11-22 12:37 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  assert(FuncDecl && "No matching function name.");
I would keep these

2021-11-22 12:38 UTC, futog commented on clang-tools-extra/test/clang-tidy/checkers/cert-msc24-c.c
> +  strcat_s(buf, BUFFSIZE, "something");
buf initialized

2021-11-22 12:38 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +          to(functionDecl(hasAnyNameFromSet(FunctionNamesWithAnnexKReplacement))
done, using fully qualified names everywhere

2021-11-22 12:39 UTC, futog commented on clang-tools-extra/docs/clang-tidy/checks/cert-msc24-c.rst
> +`qsort`, `setbuf`, `snprintf`, `sprintf`,  `sscanf`, `strcat`, `strcpy`, `strerror`,
done

2021-11-22 12:39 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  assert(Loc.isValid() && "Invalid location.");
done

2021-11-22 12:39 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +      << ReplacementFunctionName.getValue();
done

2021-11-22 12:46 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +    // caching the result
done

2021-11-22 13:04 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +      FunctionNamesWithAnnexKReplacement.contains(FunctionName))
Ok, I'm convinced. This makes the FunctionNamesWithAnnexKReplacement list unnecessary as it is. Changes made.

2021-11-22 13:12 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.h
> +  // for caching the result of useSafeFunctionsFromAnnexK
done

2021-11-22 13:21 UTC, steakhal commented on clang-tools-extra/test/clang-tidy/checkers/cert-msc24-c.c
> +  strcat_s(buf, BUFFSIZE, "something");
No, it isn't.

2021-11-22 16:32 UTC, futog commented on clang-tools-extra/docs/clang-tidy/checks/cert-msc24-c.rst
> +      // error handling
done

2021-11-22 16:35 UTC, futog commented on clang-tools-extra/docs/clang-tidy/checks/cert-msc24-c.rst
> +    fputs(buf, stderr);
done

2021-11-22 16:35 UTC, futog commented on clang-tools-extra/test/clang-tidy/checkers/cert-msc24-c.c
> +  // CHECK-MESSAGES-WITH-ANNEX-K: :[[@LINE-1]]:3: warning: function 'gets' is deprecated as of C99, removed from C11.
done

2021-11-22 16:37 UTC, futog commented on clang-tools-extra/test/clang-tidy/checkers/cert-msc24-c.c
> +  strcat_s(buf, BUFFSIZE, "something");
I meant in the correction it will be :-)

2021-11-22 16:39 UTC, futog commented on clang-tools-extra/test/clang-tidy/checkers/cert-msc24-c.c
> +  // no-warning, fseeks supports error checking
done

2021-11-22 16:43 UTC, futog commented on clang-tools-extra/docs/clang-tidy/checks/cert-msc24-c.rst
> +  void fNoWarning(const char *msg) {
done

2021-11-23 09:46 UTC, steakhal reviewed
I can't find anything really. Sweet!
WDYT about my recommendation inline?

2021-11-23 09:46 UTC, steakhal commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  } else if (const auto *FuncDecl = Result.Nodes.getNodeAs<FunctionDecl>(
This format is regression, at least in code complexity.
I would recommend something along these lines:
```c++
void ObsolescentFunctionsCheck::check(const MatchFinder::MatchResult &Result) {
  const auto *DeclRef = Result.Nodes.getNodeAs<DeclRefExpr>(DeclRefExprName);
  assert(DeclRef && "No matching declaration reference found.");
  SourceRange Range = SourceRange(DeclRef->getBeginLoc(), DeclRef->getEndLoc());

  // FIXME: I'm not sure if this can ever happen, but to be on the safe side,
  // validity is checked.
  if (Range.isInvalid())
    return;

  const auto *Normal =
      Result.Nodes.getNodeAs<FunctionDecl>(FunctionNamesExprName);
  const auto *AnnexK = Result.Nodes.getNodeAs<FunctionDecl>(
      FunctionNamesWithAnnexKReplacementExprName);
  assert((Normal && !AnnexK) || (!Normal && AnnexK));

  const StringRef FunctionName = (Normal ? Normal : AnnexK)->getName();
  assert(!FunctionName.empty());

  // Let's check the 'gets', which has no replacement.
  if (Normal && FunctionName == "gets") {
    diag(Range.getBegin(),
         "function 'gets' is deprecated as of C99, removed from C11.")
        << Range;
    return;
  }

  // If we should use a safe alternative from annex K but that's not available,
  // just return.
  if (AnnexK && !useSafeFunctionsFromAnnexK())
    return;

  std::string ReplacementFunctionName =
      AnnexK ? (Twine{FunctionName} + "_s").str()
             : StringSwitch<std::string>(FunctionName)
                   .Case("rewind", "fseek")
                   .Case("setbuf", "setvbuf");

  diag(Range.getBegin(), "function '%0' %1; '%2' should be used instead.")
      << FunctionName << getRationale(FunctionName) << ReplacementFunctionName
      << Range;
}
```
This has way less control-flow, IMO this is much more readable.

2021-11-23 10:26 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  } else if (const auto *FuncDecl = Result.Nodes.getNodeAs<FunctionDecl>(
Well, this is a different approach. For me this version is a little-bit harder to read... :-) I would like to keep it as it is.

2021-11-23 10:28 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  } else if (const auto *FuncDecl = Result.Nodes.getNodeAs<FunctionDecl>(
however, using the SourceRange is a good idea, I will incorporate that one.

2021-11-23 11:33 UTC, steakhal commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  } else if (const auto *FuncDecl = Result.Nodes.getNodeAs<FunctionDecl>(
I tell you that nesting ifs is not a good idea.
Having `Optional<std::string>`s without good justification immediately raises the question, when can the switch result in the default case? A comment is suboptimal, in almost every case documenting such things.

I don't mind a different implementation, my proposed one also has some shortcomings. You can probably rearrange the order of things to achieve an even better version.
Let me enumerate my thoughts.

I'm not using `Option<std::string>` since I already know that I must have a match, and the type also helps describe this property.
I don't have nested if blocks. Although, the `gets` check looks somewhat ugly in the middle.
After that, the early return is also weird, but it's bad only because the `useSafeFunctionsFromAnnexK()` doesn't read well in that context, so renaming that would probably resolve this.

In your code you have sideffects across two blocks of code, initializing (by assigning) the variables `FunctionName` and `ReplacementFunctionName`, which is almost always a code-smell that the code needs to be redesigned.
An Immediately called lambda expression can help in most cases, but the way I achieved this seems even better.

About the ternary switch initializer expression, yeah I agree that it's slightly complicated, but all the alternatives I thought about were even worse. This was the tersest and readable from all of them.

That being said, I don't mind other implementations, but let's keep the cognitive complexity as low as possible.
BTW the previous implementation of yours had its shortcomings, but IMO that was still better than this one.

PS: I tried to objectively summarize my proposed version in comparison to your previous and current version.
These versions will probably all pass the upstream review, I'm just pushing my //style// on you. I honestly think that a more declarative/functional coding style results in the most readable code in most cases.
Feel free to commandeer the patch and update as you wish. If I still have some thoughts, I'll add my concerns there and let the rest of the reviewers decide if they also agree on that or not. Also not that I'm not regularly submitting patches to clang-tidy, so don't add me as a reviewer, just as a subscriber if I'm not yet subscribed.

2021-11-23 11:50 UTC, futog commented on clang-tools-extra/clang-tidy/cert/ObsolescentFunctionsCheck.cpp
> +  } else if (const auto *FuncDecl = Result.Nodes.getNodeAs<FunctionDecl>(
alright, I need a little time to think about this. Maybe it is just getting used to a new style :-) It was a hard decision between the previous and the current version. I decided to do this one because during the processing of a match, I wanted to utilize the fact that when the matcher is added, we categorize the functions already ( annex K/not annex K, also different binders are added). So I wanted this to be reflected during the processing of the match. This category is processed this way, the other one is processed the other way.

Anyhow, I really appreciate the time you put into this review.

2022-05-16 13:19 UTC, closed without merging